esphome:
  name: sunrise-lamp-alarm-esp
  friendly_name: Sunrise Lamp Alarm ESP

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

logger:
  level: DEBUG

api:
  encryption:
    key: "Your_API_Encryption_Key" #TODO: Change this to your API encryption key

ota:
  - platform: esphome
    password: "Your_OTA_Password" #TODO: Change this to your OTA password

wifi:
  ssid: "Your_WiFi_SSID" #TODO: Change this to your WiFi SSID
  password: "Your_WiFi_Password" #TODO: Change this to your WiFi password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sunrise Lamp Alarm Fallback Hotspot"
    password: "Your_Fallback_Password" #TODO: Change this to your fallback password

captive_portal:

# https://esphome.io/components/light/neopixelbus/
light:
  - platform: neopixelbus
    type: GRBW
    variant: WS2812
    pin: gpio18
    num_leds: 60
    name: "Sunrise Lamp Light"

# https://esphome.io/components/binary_sensor/gpio/
binary_sensor:
  - platform: gpio
    pin:
      number: gpio2
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Sunrise Lamp Alarm Button"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s